# Generated by Django 6.0 on 2026-01-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='fullname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
