# Generated by Django 6.0 on 2026-01-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_address_fullname_address_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='fullname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
